# FAKE NEWS CLASSIFIER USING LSTM

### 1. dataset ## 
### 2. Independant and Dependant Features
### 3. Cleaning the Data --> 1. Stemming 2.Stopwords 
### 4. Fix a setence length to fix the input 
### 5. One Hot Representation , Embedding layer 
### 6. LSTM Neural Network

In [226]:
import pandas as pd 
import numpy as np

In [227]:
# df=pd.read_csv('train.csv',error_bad_lines=false ,engine='python')

In [228]:
data = pd.read_csv('train.csv')
data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [229]:
data.shape

(20800, 5)

In [230]:
data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

Since this is a text data we cannot replace the null values so we have to drop it 

In [231]:
data = data.dropna()

In [232]:
data.isnull().sum().sum()

0

Independant features

In [233]:
X= data.drop('label',axis=1)
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

Dependant Feature 

In [234]:
y = data['label']

In [235]:
X.shape 

(18285, 4)

In [236]:
y.shape

(18285,)

In [237]:
import tensorflow as tf

In [238]:
print(tf.__version__)

2.15.0


In [239]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [240]:
voc_size = 5000

One Hot Encoding

In [241]:
sentences = X.copy()

In [242]:
sentences['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [243]:
sentences.reset_index(inplace=True)

In [244]:
sentences

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [245]:
import nltk
import re
from nltk.corpus import stopwords

In [246]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [247]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ',sentences['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [248]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

OHE

In [249]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1617, 306, 921, 3920, 4710, 777, 1386, 1303, 3682, 3430],
 [3105, 884, 124, 3352, 3579, 401, 4090],
 [4873, 152, 4395, 1728],
 [974, 791, 3274, 347, 762, 1995],
 [541, 3579, 4319, 1542, 3679, 4958, 3579, 3113, 1735, 3484],
 [1391,
  3823,
  4923,
  1502,
  4782,
  3596,
  2409,
  1130,
  2424,
  611,
  3886,
  3899,
  431,
  4262,
  4090],
 [2534, 2981, 550, 539, 600, 953, 1760, 2197, 3719, 553, 112],
 [2174, 1455, 1424, 1277, 3365, 4292, 3596, 3943, 3719, 553, 112],
 [4346, 4983, 935, 2020, 3027, 3728, 447, 3655, 3596, 4],
 [2051, 3353, 4329, 3652, 2917, 1585, 1707, 2545],
 [3889, 838, 3674, 2374, 765, 4921, 2835, 2882, 2365, 3323, 4899],
 [347, 1194, 4710, 3728, 3596, 3365],
 [4442, 2206, 3801, 626, 4709, 4205, 2505, 4642, 2906],
 [4300, 3526, 4243, 3269, 1762, 3644, 4452, 3719, 553, 112],
 [667, 824, 1867, 1405, 4903, 3719, 553, 112],
 [164, 4961, 4813, 416, 1396, 1923, 1671, 1433, 623, 4903],
 [4597, 1531, 884],
 [4645, 3254, 2043, 1114, 3596, 968, 1082, 4090],
 [1615, 4662, 124,

Embedding Representation

In [250]:
## pre padding
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1303 3682 3430]
 [   0    0    0 ... 3579  401 4090]
 [   0    0    0 ...  152 4395 1728]
 ...
 [   0    0    0 ... 3719  553  112]
 [   0    0    0 ... 4612 1533 4676]
 [   0    0    0 ... 4849  775 1810]]


In [251]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1617,
        306,  921, 3920, 4710,  777, 1386, 1303, 3682, 3430])

In [252]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_17 (Embedding)    (None, 20, 40)            200000    
                                                                 
 lstm_17 (LSTM)              (None, 100)               56400     
                                                                 
 dense_17 (Dense)            (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [253]:
len(embedded_docs),y.shape

(18285, (18285,))

In [254]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [255]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

Model Training

In [256]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10


192/192 [==============================] - 5s 15ms/step - loss: 0.3412 - accuracy: 0.8407 - val_loss: 0.1972 - val_accuracy: 0.9143
Epoch 2/10
192/192 [==============================] - 3s 15ms/step - loss: 0.1427 - accuracy: 0.9445 - val_loss: 0.2116 - val_accuracy: 0.9170
Epoch 3/10
192/192 [==============================] - 3s 18ms/step - loss: 0.1012 - accuracy: 0.9623 - val_loss: 0.2204 - val_accuracy: 0.9114
Epoch 4/10
192/192 [==============================] - 4s 18ms/step - loss: 0.0721 - accuracy: 0.9743 - val_loss: 0.2915 - val_accuracy: 0.9143
Epoch 5/10
192/192 [==============================] - 4s 18ms/step - loss: 0.0469 - accuracy: 0.9827 - val_loss: 0.3134 - val_accuracy: 0.9123
Epoch 6/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0301 - accuracy: 0.9906 - val_loss: 0.3994 - val_accuracy: 0.9090
Epoch 7/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0188 - accuracy: 0.9951 - val_loss: 0.4511 - val_accuracy: 0.9077
Epoch 8/10

Adding Dropout

In [257]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Performance Metrics And Accuracy

In [258]:
y_pred=model.predict(X_test)

189/189 [==============================] - 1s 4ms/step


In [259]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [260]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

In [261]:
'''y_pred = model.predict(X_test)

# Calculate the ROC curve and AUC
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr) '''

'y_pred = model.predict(X_test)\n\n# Calculate the ROC curve and AUC\nfpr, tpr, thresholds = roc_curve(y_test, y_pred)\nroc_auc = auc(fpr, tpr) '

In [262]:
# Plot ROC curve
'''plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show() '''

'plt.figure()\nplt.plot(fpr, tpr, color=\'darkorange\', lw=2, label=\'ROC curve (area = %0.2f)\' % roc_auc)\nplt.plot([0, 1], [0, 1], color=\'navy\', lw=2, linestyle=\'--\')\nplt.xlim([0.0, 1.0])\nplt.ylim([0.0, 1.05])\nplt.xlabel(\'False Positive Rate\')\nplt.ylabel(\'True Positive Rate\')\nplt.title(\'Receiver Operating Characteristic (ROC) Curve\')\nplt.legend(loc="lower right")\nplt.show() '

In [263]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [264]:
from sklearn.metrics import confusion_matrix

In [265]:
confusion_matrix(y_test,y_pred)

array([[2908,  511],
       [1934,  682]], dtype=int64)

In [266]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5948632974316487

In [267]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.60      0.85      0.70      3419
           1       0.57      0.26      0.36      2616

    accuracy                           0.59      6035
   macro avg       0.59      0.56      0.53      6035
weighted avg       0.59      0.59      0.55      6035

