In [1]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [36]:
sent = ['a cat chased mice eagerly',
        'birds chirped loudly outside',
        'the sun shone brightly overhead' ,
        'raindrops fell softly, steadily',
        'children laughed joyfully, playing outside',
        'flowers bloomed beautifully in gardens',
        'the wind whispered secrets gently']

In [37]:
sent

['a cat chased mice eagerly',
 'birds chirped loudly outside',
 'the sun shone brightly overhead',
 'raindrops fell softly, steadily',
 'children laughed joyfully, playing outside',
 'flowers bloomed beautifully in gardens',
 'the wind whispered secrets gently']

In [40]:
## You should specificallly mention the Vocabulary size
#say ,
voc_size = 10000

#the larger voc size means the larger feature representation you gonna get

## One Hot Encoding

In [39]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[2497, 7363, 4683, 5423, 4867], [1410, 8563, 7621, 5685], [1445, 8935, 722, 9767, 1686], [2538, 7524, 7279, 2594], [8765, 3874, 7414, 5193, 5685], [2755, 7797, 4870, 8367, 1173], [1445, 829, 5471, 3603, 5116]]


As you see the vocabulary size of each sentence is different . In neural networds inorder to train the models the size should be fixed or should be of equal size.

So we are going to do **prepadding and post padding**

## Word Embedding Representation

In [41]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [42]:
import numpy as np

**Prepadding**

In [46]:
sent_length=6
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0 2497 7363 4683 5423 4867]
 [   0    0 1410 8563 7621 5685]
 [   0 1445 8935  722 9767 1686]
 [   0    0 2538 7524 7279 2594]
 [   0 8765 3874 7414 5193 5685]
 [   0 2755 7797 4870 8367 1173]
 [   0 1445  829 5471 3603 5116]]


**Postpadding**

In [47]:
sent_length=6
embedded_docs=pad_sequences(onehot_rep,padding='post',maxlen=sent_length)
print(embedded_docs)

[[2497 7363 4683 5423 4867    0]
 [1410 8563 7621 5685    0    0]
 [1445 8935  722 9767 1686    0]
 [2538 7524 7279 2594    0    0]
 [8765 3874 7414 5193 5685    0]
 [2755 7797 4870 8367 1173    0]
 [1445  829 5471 3603 5116    0]]


Now we have to convert each and every value to vectors

In [51]:
dim=10 #feature representation

In [49]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [50]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [53]:
embedded_docs[0]

array([2497, 7363, 4683, 5423, 4867,    0], dtype=int32)

In [52]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 120ms/step


array([[ 0.01575037,  0.00657766, -0.00341181,  0.04891651, -0.02684499,
        -0.00349045,  0.03433845,  0.0156437 ,  0.01099253,  0.035834  ],
       [ 0.01452811, -0.04468718, -0.01522182, -0.00552497,  0.04648506,
        -0.04169091, -0.04268931, -0.03297973,  0.02919353, -0.0290315 ],
       [ 0.01087821, -0.00570152,  0.04836578, -0.00329616,  0.04430432,
         0.0070483 , -0.01467556, -0.00146109,  0.0085188 ,  0.02241153],
       [-0.01207951, -0.02120587, -0.00305631, -0.00450524, -0.00044464,
        -0.04658449,  0.02420778,  0.01160377,  0.02501697, -0.04734511],
       [-0.01639165,  0.04157256,  0.03324279, -0.03139301, -0.03876275,
         0.02287107,  0.03240244,  0.03022284,  0.03666368, -0.02100646],
       [-0.02821031, -0.04106817,  0.04485799, -0.02013882,  0.04745186,
        -0.01806557,  0.01379782, -0.03392436,  0.02320048,  0.01766099]],
      dtype=float32)

1.
**2497** represented by [ 0.01575037,  0.00657766, -0.00341181,  0.04891651, -0.02684499,
        -0.00349045,  0.03433845,  0.0156437 ,  0.01099253,  0.035834  ]

2.
**7363** by **[ 0.01452811, -0.04468718, -0.01522182, -0.00552497,  0.04648506,
        -0.04169091, -0.04268931, -0.03297973,  0.02919353, -0.0290315 ]**
and so on





In [54]:
##Assignment

In [55]:
sent2=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [56]:
sent2

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [65]:
voca_size = 500

In [66]:
onehot_rep2=[one_hot(words,voc_size)for words in sent2]
print(onehot_rep2)

[[161, 243, 86, 99, 157, 171], [397, 495, 86, 67, 186, 372], [223, 327, 241, 103], [161, 421, 86, 283, 161, 245], [210, 224, 262, 86, 67, 186, 372], [496, 86, 67, 186, 63, 296]]


In [67]:
sent_length=7
embedded_docs2=pad_sequences(onehot_rep2,padding='pre',maxlen=sent_length)
print(embedded_docs2)

[[  0 161 243  86  99 157 171]
 [  0 397 495  86  67 186 372]
 [  0   0   0 223 327 241 103]
 [  0 161 421  86 283 161 245]
 [210 224 262  86  67 186 372]
 [  0 496  86  67 186  63 296]]


In [68]:
model=Sequential()
model.add(Embedding(voca_size,10,input_length=sent_length))
model.compile('adam','mse')

In [69]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 7, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [71]:
embedded_docs2[0]

array([  0, 161, 243,  86,  99, 157, 171], dtype=int32)

In [72]:
model.predict(embedded_docs2[0])

1/1 [==============================] - 0s 34ms/step


array([[ 0.04047849, -0.01689198, -0.01246122,  0.04725632, -0.01913021,
        -0.04884465,  0.01238566,  0.02327514, -0.04993438,  0.0001057 ],
       [-0.02065299,  0.0071115 ,  0.01745811,  0.04357481,  0.045478  ,
         0.02574242,  0.03804786,  0.0306913 ,  0.01552041,  0.00719967],
       [ 0.00922886, -0.00662612, -0.04062014,  0.03122893,  0.01248633,
         0.01539804, -0.00892782,  0.02763195, -0.04033942, -0.0471788 ],
       [-0.00591771, -0.02982156, -0.0491829 , -0.02814266, -0.00651181,
        -0.00827789, -0.03749899,  0.03611115, -0.04828398,  0.01865507],
       [ 0.04321885,  0.04268974, -0.00226673, -0.01358521,  0.00650729,
        -0.02142714,  0.02528242, -0.0067343 , -0.00825801, -0.03284285],
       [ 0.0487203 ,  0.00625074, -0.04429381,  0.03469982, -0.02159597,
         0.00038975, -0.01991975, -0.04801899,  0.0156932 ,  0.04849735],
       [-0.01614556,  0.03799892,  0.01109544, -0.0065308 , -0.03701038,
        -0.04296234, -0.04524186, -0.01058452

In [73]:
model.predict(embedded_docs2)

1/1 [==============================] - 0s 34ms/step


array([[[ 0.04047849, -0.01689198, -0.01246122,  0.04725632,
         -0.01913021, -0.04884465,  0.01238566,  0.02327514,
         -0.04993438,  0.0001057 ],
        [-0.02065299,  0.0071115 ,  0.01745811,  0.04357481,
          0.045478  ,  0.02574242,  0.03804786,  0.0306913 ,
          0.01552041,  0.00719967],
        [ 0.00922886, -0.00662612, -0.04062014,  0.03122893,
          0.01248633,  0.01539804, -0.00892782,  0.02763195,
         -0.04033942, -0.0471788 ],
        [-0.00591771, -0.02982156, -0.0491829 , -0.02814266,
         -0.00651181, -0.00827789, -0.03749899,  0.03611115,
         -0.04828398,  0.01865507],
        [ 0.04321885,  0.04268974, -0.00226673, -0.01358521,
          0.00650729, -0.02142714,  0.02528242, -0.0067343 ,
         -0.00825801, -0.03284285],
        [ 0.0487203 ,  0.00625074, -0.04429381,  0.03469982,
         -0.02159597,  0.00038975, -0.01991975, -0.04801899,
          0.0156932 ,  0.04849735],
        [-0.01614556,  0.03799892,  0.01109544, -0.0